### PR TITLE
Add artifact name as input

### PR DESCRIPTION
**Pull request by AlexDHoffer**
Allow users to configure custom report names by providing an optional Action input. Requires this to go in: https://github.com/zaproxy/actions-common/pull/15

Merging in both resolves https://github.com/zaproxy/action-baseline/issues/45

### CODE REVIEW

**Comment by thc202** [comment]
The changelog should be updated as well.

**Comment by tony** [comment]
> This is now waiting for the release of common library.

@thc202 Regarding [common library](https://github.com/zaproxy/actions-common) having a new version released, is it possible to tag a new release now (e.g. `v0.3.0`), or possibly backport this if there's been breaking changes (i.e. `v0.2.1`)?

@AlexDHoffer: Wouldn't this need to also be PR'd to https://github.com/zaproxy/action-full-scan and https://github.com/zaproxy/action-api-scan?

**Comment by erichiggins** [comment]
This PR is over a year old and the issue persists. Could we get a status update on this, please?

**Comment by thc202** [comment]
There's nothing to update, the common library still needs to be released.

**Comment by thc202** [comment]
The library has been released, it will be updated soon.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
