### PR TITLE
chore: Add check-dist workflow

### PR DESCRIPTION
**Pull request by kingthorin**
As discussed via email.
Also update .gitignore to include eclipse artifacts.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Flattened

**Review by thc202 — APPROVED** [review]

**Comment by kingthorin** [comment]
Further updates coming as discussed via IRC :wink:

**Comment by kingthorin** [comment]
Now with dist regenerated

**Comment by kingthorin** [comment]
Wow that's quite a difference in content..... let me check one more thing. Might need a rebase.

**Comment by kingthorin** [comment]
Ok, seems correct from my point of view.

**Comment by kingthorin** [comment]
This is still bothering me, the test repo also only has a 2 line change. I'll try to investigate further.

**Comment by kingthorin** [comment]
There we go. It must have been an order of operations issue (which order/issue I'm not exactly sure but after a bunch of trial and error it seems sorted). It now looks as I had expected.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
