### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Used `npm audit fix --force` so not too surprised it failed

**Comment by kingthorin** [comment]
You'll need to regenerate it.

**Comment by kingthorin** [comment]
Hmmm looks like the actual build itself is failing.

**Comment by psiinon** [comment]
It is, which wasnt a huge surprise, but I'm hoping  the error messages will help me fix it...

**Comment by kingthorin** [comment]
It built that time, the new code is attached to the run as an artifact.

**Comment by psiinon** [comment]
It worked 😮

**Review by kingthorin — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
@psiinon do you want to double check? (You'll not be able to approve though.)

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
But you can merge if it looks good :)

**Pull request merged**
