### PR TITLE
Prepare next dev version

### PR DESCRIPTION
**Pull request by thc202**
Add unreleased entry to changelog.

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
FYI it seems there's a bug with "paths-ignore" per: https://github.com/actions/runner/issues/2324

Per various PRs we might need to do a workaround such as: https://github.com/kairos-io/kairos/commit/da09301a2455481ab5edc01fa9aa58e20ceeb71c

**Comment by thc202** [comment]
That will not change anything for us though, we will still have to merge bypassing protections.

**Comment by kingthorin** [comment]
But if the workflow isn't triggered then it should be okay.

**Comment by thc202** [comment]
The workflows are not triggered, that's why we need to bypass.

**Pull request merged**
