### PR TITLE
Use of non root user, zap options and custom reports dir

### PR DESCRIPTION
**Pull request by juanmatias**
I was trying to use image ictu/zap2docker-weekly with this action. This because I need to login into the site with user and pwd.
To accomplish this I changed these:
  - the ability to run the container as a non root user
  - the ability of handling zap parameters in a better way
  - the ability to set a different reports base dir

If no parameters added, the defaults are to use root user, to have an empty string as zap parameters and to user current dir as base for reports.

In the readme it is explained and I added a simple example on how to use the after-mentioned image creating and publishing a report as artifact.

### CODE REVIEW

**Comment by sshniro** [comment]
Thank you for the contribution, I'll test this over the weekend.

**Comment by juanmatias** [comment]
@thc202 sorry for the late reply, the branch was rebased, conflicts solved and all commits merged into one. Please, let me know what else I can do.

**Comment by sshniro** [comment]
Hi @juanmatias , I was not able to run this previously. Unfortunately, I can test this on Friday only. I will test and update the results. Apart from it, the code LGTM!

**Comment by psiinon** [comment]
For info the root user is no longer used as per https://github.com/zaproxy/action-baseline/pull/77

**Comment by thc202** [comment]
Closing, for authentication and more customization it's better to use the [Automation Framework](https://www.zaproxy.org/docs/automate/automation-framework/) and its action.

**Pull request closed without merging**
